pipeline {

  agent none

  triggers {
    githubPush()
  }

  environment {
    IMAGE_TAG = "${BUILD_NUMBER}"
    DOCKERHUB_USER = "bera1998"
    SONAR_URL = "http://52.23.249.181:9000"
  }

  stages {

    /* ================= CHECKOUT ================= */
    stage('Checkout Code') {
      agent any
      steps {
        checkout scm
      }
    }

    /* ================= FRONTEND SCAN ================= */
    stage('Frontend Scan') {
      agent {
        docker {
          image 'sonarsource/sonar-scanner-cli'
        }
      }
      steps {
        dir('Frontend') {
          withSonarQubeEnv('sonar-server') {
            sh '''
              sonar-scanner \
              -Dsonar.projectKey=frontend-app \
              -Dsonar.sources=src
            '''
          }
        }
      }
    }

    /* ================= FRONTEND IMAGE ================= */
    stage('Build & Push Frontend Image') {
      agent any
      steps {
        dir('Frontend') {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              docker build -t $DOCKER_USER/frontend-app:$IMAGE_TAG .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push $DOCKER_USER/frontend-app:$IMAGE_TAG
            '''
          }
        }
      }
    }

    /* ================= BACKEND SCAN ================= */
    stage('Backend Scan') {
      agent {
        docker {
          image 'sonarsource/sonar-scanner-cli'
        }
      }
      steps {
        dir('backend') {
          withSonarQubeEnv('sonar-server') {
            sh '''
              sonar-scanner \
              -Dsonar.projectKey=backend-app \
              -Dsonar.sources=.
            '''
          }
        }
      }
    }

    /* ================= BACKEND IMAGE ================= */
    stage('Build & Push Backend Image') {
      agent any
      steps {
        dir('backend') {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              docker build -t $DOCKER_USER/backend-app:$IMAGE_TAG .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push $DOCKER_USER/backend-app:$IMAGE_TAG
            '''
          }
        }
      }
    }

    /* ================= UPDATE K8S YAML ================= */
    stage('Update Kubernetes Manifests') {
      agent any
      steps {
        sh '''
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/frontend-deployment.yaml
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/backend-deployment.yaml
        '''
      }
    }

    /* ================= GITOPS COMMIT ================= */
    stage('Commit & Push for ArgoCD') {
      agent any
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'github-pat',
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
            git config user.email "jenkins@ci.com"
            git config user.name "jenkins"

            git add k8s/

            git diff --quiet || git commit -m "[ci skip] Update image tags to $IMAGE_TAG"

            git push https://$GIT_USER:$GIT_TOKEN@github.com/bera1998/3-tire-end-to-end.git main
          '''
        }
      }
    }

  }
}